# Generated by Django 4.0.6 on 2022-07-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre de cliente')),
                ('correoCliente', models.EmailField(max_length=254, verbose_name='Email del cliente')),
                ('fonoCliente', models.CharField(max_length=9, verbose_name='Telefono cliente')),
                ('direCliente', models.CharField(max_length=100, verbose_name='Direccion del cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
